import Head from "next/head";
import Image from 'next/image';
import { ReactElement } from "react";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";

function Home(): ReactElement {
	const handleOnBannerBtnClick = () => {
		console.log("Hi Banner button");
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
				<div className={styles.heroImage}>
					<Image src="/static/hero-image.png" width={700} height={400} />
				</div>
			</main>
		</div>
	);
}

export default Home;
